const lang = {
  en: { search: "Search", GptSearchPlaceholder: "What do you want to watch today?" }, // English (USA, UK)
  es: { search: "Buscar", GptSearchPlaceholder: "¿Qué quieres ver hoy?" }, // Spanish (Spain, LATAM)
  fr: { search: "Recherche", GptSearchPlaceholder: "Que voulez-vous regarder aujourd'hui ?" }, // French (France)
  de: { search: "Suchen", GptSearchPlaceholder: "Was möchtest du heute anschauen?" }, // German (Germany)
  it: { search: "Cerca", GptSearchPlaceholder: "Cosa vuoi guardare oggi?" }, // Italian (Italy)
  pt: { search: "Pesquisar", GptSearchPlaceholder: "O que você quer assistir hoje?" }, // Portuguese (Portugal/Brazil)
  ru: { search: "Поиск", GptSearchPlaceholder: "Что вы хотите посмотреть сегодня?" }, // Russian (Russia)
  zh: { search: "搜索", GptSearchPlaceholder: "你今天想看什么？" }, // Chinese (Simplified)
  ja: { search: "検索", GptSearchPlaceholder: "今日は何を見たいですか？" }, // Japanese (Japan)
  ko: { search: "검색", GptSearchPlaceholder: "오늘 무엇을 보고 싶나요?" }, // Korean (South Korea)
  ar: { search: "بحث", GptSearchPlaceholder: "ماذا تريد أن تشاهد اليوم؟" }, // Arabic (Middle East)
  hi: { search: "खोज", GptSearchPlaceholder: "आप आज क्या देखना चाहते हैं?" }, // Hindi (India)
  tr: { search: "Ara", GptSearchPlaceholder: "Bugün ne izlemek istersin?" }, // Turkish (Turkey)
  nl: { search: "Zoeken", GptSearchPlaceholder: "Wat wil je vandaag kijken?" }, // Dutch (Netherlands)
  pl: { search: "Szukaj", GptSearchPlaceholder: "Co chcesz dziś obejrzeć?" }, // Polish (Poland)
  sv: { search: "Sök", GptSearchPlaceholder: "Vad vill du titta på idag?" }, // Swedish (Sweden)
  da: { search: "Søg", GptSearchPlaceholder: "Hvad vil du se i dag?" }, // Danish (Denmark)
  fi: { search: "Hae", GptSearchPlaceholder: "Mitä haluat katsoa tänään?" }, // Finnish (Finland)
  no: { search: "Søk", GptSearchPlaceholder: "Hva vil du se i dag?" }, // Norwegian (Norway)
  el: { search: "Αναζήτηση", GptSearchPlaceholder: "Τι θέλετε να παρακολουθήσετε σήμερα;" }, // Greek (Greece)
  cs: { search: "Vyhledávání", GptSearchPlaceholder: "Na co se dnes chcete podívat?" }, // Czech (Czechia)
  hu: { search: "Keresés", GptSearchPlaceholder: "Mit szeretnél ma nézni?" }, // Hungarian (Hungary)
  ro: { search: "Caută", GptSearchPlaceholder: "Ce vrei să vizionezi astăzi?" }, // Romanian (Romania)
  bg: { search: "Търсене", GptSearchPlaceholder: "Какво искате да гледате днес?" }, // Bulgarian (Bulgaria)
  he: { search: "חיפוש", GptSearchPlaceholder: "מה תרצה לצפות היום?" }, // Hebrew (Israel)
  id: { search: "Cari", GptSearchPlaceholder: "Ingin menonton apa hari ini?" }, // Indonesian (Indonesia)
  th: { search: "ค้นหา", GptSearchPlaceholder: "วันนี้คุณอยากดูอะไร?" }, // Thai (Thailand)
  vi: { search: "Tìm kiếm", GptSearchPlaceholder: "Bạn muốn xem gì hôm nay?" }, // Vietnamese (Vietnam)
  uk: { search: "Пошук", GptSearchPlaceholder: "Що ви хочете подивитися сьогодні?" }, // Ukrainian (Ukraine)
  ms: { search: "Cari", GptSearchPlaceholder: "Apa yang anda mahu tonton hari ini?" }, // Malay (Malaysia)
  fa: { search: "جستجو", GptSearchPlaceholder: "امروز دوست دارید چه چیزی تماشا کنید؟" }, // Persian (Iran)
  bn: { search: "অনুসন্ধান", GptSearchPlaceholder: "আজ আপনি কী দেখতে চান?" }, // Bengali (Bangladesh/India)
  ur: { search: "تلاش کریں", GptSearchPlaceholder: "آج آپ کیا دیکھنا چاہتے ہیں؟" }, // Urdu (Pakistan)
  ta: { search: "தேடு", GptSearchPlaceholder: "இன்று நீங்கள் என்ன பார்க்க விரும்புகிறீர்கள்?" }, // Tamil (India)
  te: { search: "వెతకండి", GptSearchPlaceholder: "మీరుఈరోజు ఏమి చూడాలనుకుంటున్నారు?" }, // Telugu (India)
  ml: { search: "തിരയൂ", GptSearchPlaceholder: "ഇന്ന് നിങ്ങൾ എന്താണ് കാണാൻ ആഗ്രഹിക്കുന്നത്?" }, // Malayalam (India)
  kn: { search: "ಹುಡುಕಿ", GptSearchPlaceholder: "ನೀವು ಇಂದು 무엇을 ನೋಡಲು ಇಚ್ಛಿಸುತ್ತೀರಿ?" }, // Kannada (India)
  mr: { search: "शोधा", GptSearchPlaceholder: "आज तुम्हाला काय बघायचं आहे?" }, // Marathi (India)
  sq: { search: "Kërko", GptSearchPlaceholder: "Çfarë dëshironi të shihni sot?" }, // Albanian (Albania)
  sr: { search: "Претрага", GptSearchPlaceholder: "Шта желите да гледате данас?" }, // Serbian (Serbia)
  sk: { search: "Hľadať", GptSearchPlaceholder: "Čo chcete dnes pozerať?" }, // Slovak (Slovakia)
  hr: { search: "Traži", GptSearchPlaceholder: "Što želiš gledati danas?" }, // Croatian (Croatia)
  sl: { search: "Išči", GptSearchPlaceholder: "Kaj želite gledati danes?" }, // Slovenian (Slovenia)
  et: { search: "Otsi", GptSearchPlaceholder: "Mida sa täna vaadata tahad?" }, // Estonian (Estonia)
  lt: { search: "Ieškoti", GptSearchPlaceholder: "Ką norite šiandien žiūrėti?" }, // Lithuanian (Lithuania)
  lv: { search: "Meklēt", GptSearchPlaceholder: "Ko jūs vēlaties skatīties šodien?" }, // Latvian (Latvia)
  af: { search: "Soek", GptSearchPlaceholder: "Wat wil jy vandag kyk?" }, // Afrikaans (South Africa)
  sw: { search: "Tafuta", GptSearchPlaceholder: "Ungependa kutazama nini leo?" }, // Swahili (Kenya/Tanzania)
  zu: { search: "Sesha", GptSearchPlaceholder: "Ufuna ukubuka ini namhlanje?" }, // Zulu (South Africa)
  fil: { search: "Maghanap", GptSearchPlaceholder: "Ano ang gusto mong panoorin ngayon?" }, // Filipino (Philippines)
  ro: { search: "Caută", GptSearchPlaceholder: "Ce vrei să vizionezi astăzi?" }, // Romanian (Romania)
  is: { search: "Leita", GptSearchPlaceholder: "Hvað viltu horfa á í dag?" }, // Icelandic (Iceland)
};
export default lang;